DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
  ID INT PRIMARY KEY,
  ACCOUNTNUMBER INTEGER NOT NULL,
  ACCOUNTTYPE VARCHAR(250),
  BALANCE DECIMAL(10,2)
);
INSERT INTO ACCOUNT (ID, ACCOUNTNUMBER, ACCOUNTTYPE, BALANCE) VALUES (1, 1236, 'Savings', 100.0);
INSERT INTO ACCOUNT (ID, ACCOUNTNUMBER, ACCOUNTTYPE, BALANCE) VALUES (2, 2347, 'Current', 200.0);

